version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tempsense"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kqze03zxmezi"
s3_prefix = "tempsense"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
